# Generated by Django 2.1.7 on 2019-02-23 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 0, 56, 21, 32114)),
        ),
    ]
